### ISSUE TITLE
Hi, I have a simple question !

### ISSUE THREAD

**Issue by sung-won-kim** [SongW-SW/TENT#2]
https://github.com/SongW-SW/TENT/blob/a948a8083546df8a34295acb3597cc1cd8fb915d/train_TENT.py#L526

Hi, thank you for sharing your code, and nice research.

Regarding the code at building virtual node with taking a average of class's support nodes,
I'm wondering why are you taking a mean of `emb_features[pos_node_idx]`. 

I guess `pos_node_idx` contains sampled support nodes of task (not specified by classes), so I think `emb_features[class_pos_idx]` is right. 

Am I misunderstanding something? 

Thank you.

**Comment by SongW-SW** [comment]
Hi Sungwon,

Thank you for your interest in our work! 
And indeed, I think you are right. This line should be emb_features[class_pos_idx]. I have fixed it in the code. 
Thank you so much for pointing this out! I'm really sorry for the inconvenience here.
