### ISSUE TITLE
ValueError about inputs

### ISSUE THREAD

**Issue by dtjayaaa12345** [SongW-SW/TENT#3]
Hi, thanks for sharing source code. I used the provided dataset.zip and ran train_TENT.py without any modifcation, but it reports the following errors:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/14312872/189285163-5464c6d7-426a-4973-afc4-1653f7033a39.png">
Is there any problem in used cora-full dataset?

**Comment by SongW-SW** [comment]
Sorry for the late reply! I have updated the code to solve this problem, which is caused by the l2_normalize function. It should work now.
